apiVersion: v1
kind: Route
metadata:
  labels:
    app: hangman
  name: hangman
spec:
  host: hangman.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hangman
    weight: 100
